include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/docker-dedicated-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy-v2.gitlab-ci.yaml"

stages:
  - build
  - deploy

build:
  only:
    - docs
  except:
    - tags
  extends: .build:common

deploy:prod:
  only:
    - docs
  except:
    - tags
  extends: .deploy
  variables:
    K8S_NAMESPACE: broxus
    APP_CONFIG: ""
  environment:
    name: prod
    on_stop: stop:prod
  tags: ["broxus-pve-main"]

stop:prod:
  only:
    - docs
  except:
    - tags
  extends: .stop
  variables:
    K8S_NAMESPACE: broxus
    APP_CONFIG: ""
  environment:
    name: prod
  tags: ["broxus-pve-main"]
